[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Serverless functions configuration
[functions]
  directory = ".output/server"

# Handle all routes through Nuxt
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
